# Generated by Django 4.1.5 on 2023-01-05 17:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Planning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "start",
                    models.CharField(
                        choices=[
                            ("January", "January"),
                            ("February", "February"),
                            ("March", "March"),
                            ("April", "April"),
                            ("May", "May"),
                            ("June", "June"),
                            ("July", "July"),
                            ("August", "August"),
                            ("September", "September"),
                            ("October", "October"),
                            ("November", "November"),
                            ("December", "December"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "planning_cycle",
                    models.CharField(
                        choices=[
                            ("Month", "Month"),
                            ("Year", "Year"),
                            ("Semester", "Semester"),
                        ],
                        max_length=10,
                    ),
                ),
                ("number_of_cycles", models.IntegerField(default=1)),
                ("expense", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning",
                        to="categories.categories",
                    ),
                ),
            ],
        ),
    ]
