# Generated by Django 4.1.5 on 2023-01-11 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Planning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "start",
                    models.IntegerField(
                        choices=[
                            (1, "Jan"),
                            (2, "Feb"),
                            (3, "Mar"),
                            (4, "Apr"),
                            (5, "May"),
                            (6, "Jun"),
                            (7, "Jul"),
                            (8, "Aug"),
                            (9, "Sep"),
                            (10, "Oct"),
                            (11, "Nov"),
                            (12, "Dec"),
                        ]
                    ),
                ),
                (
                    "planning_cycle",
                    models.CharField(
                        choices=[("Month", "Month"), ("Year", "Year")], max_length=10
                    ),
                ),
                ("number_of_cycles", models.PositiveIntegerField(default=1)),
                ("expense", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plannings",
                        to="accounts.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning",
                        to="categories.categories",
                    ),
                ),
            ],
        ),
    ]
