# Generated by Django 4.1.5 on 2023-01-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plannings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planning",
            name="planning_cycle",
            field=models.CharField(
                choices=[
                    ("Month", "Month"),
                    ("Year", "Year"),
                    ("Semester", "Semester"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="planning",
            name="start",
            field=models.CharField(
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "Jun"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                max_length=10,
            ),
        ),
    ]
