# Generated by Django 4.1.5 on 2023-01-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plannings", "0002_alter_planning_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planning",
            name="start",
            field=models.CharField(
                choices=[
                    (1, "Jan"),
                    (2, "Feb"),
                    (3, "Mar"),
                    (4, "Apr"),
                    (5, "May"),
                    (6, "Jun"),
                    (7, "Jul"),
                    (8, "Aug"),
                    (9, "Sep"),
                    (10, "Oct"),
                    (11, "Nov"),
                    (12, "Dec"),
                ],
                max_length=10,
            ),
        ),
    ]
