# Generated by Django 4.1.5 on 2023-01-04 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_categories_name"),
        ("plannings", "0002_alter_planning_planning_cycle_alter_planning_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planning",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planning",
                to="categories.categories",
            ),
        ),
        migrations.AlterField(
            model_name="planning",
            name="start",
            field=models.CharField(
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                max_length=10,
            ),
        ),
    ]
