# Generated by Django 4.1.5 on 2023-01-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[("checking", "Cc"), ("savings", "Cp")],
                default="checking",
                max_length=20,
            ),
        ),
    ]
