# Generated by Django 4.1.5 on 2023-01-04 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description", models.CharField(max_length=255)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("payment", "Pmt"), ("receipt", "Rct")],
                        default="receipt",
                        max_length=7,
                    ),
                ),
                ("transaction_date", models.DateField()),
            ],
        ),
    ]
