# Generated by Django 4.1.5 on 2023-01-05 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("categories", "0001_initial"),
        ("transactions", "0002_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounts.account",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="categories.categories",
            ),
            preserve_default=False,
        ),
    ]
